<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-SQI1G9P" ignored="0" name="Create customer API Test" tests="6" failures="3" timestamp="2021-12-28T00:50:46 IST" time="2.596" errors="0">
  <testcase name="validateCreatecustomerAPIwithvalidSecretKey" time="2.451" classname="com.w2a.testingfranwork.testcases.createCustomerTest"/>
  <testcase name="validateCreatecustomerAPIwithvalidSecretKey" time="2.451" classname="com.w2a.testingfranwork.testcases.createCustomerTest"/>
  <testcase name="deleteCustomer" time="2.456" classname="com.w2a.testingfranwork.testcases.DeleteCutsomerTest">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.w2a.testingfranwork.testcases.DeleteCutsomerTest.deleteCustomer(DeleteCutsomerTest.java:44)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="2.457" classname="com.w2a.testingfranwork.testcases.DeleteCutsomerTest">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.w2a.testingfranwork.testcases.DeleteCutsomerTest.deleteCustomer(DeleteCutsomerTest.java:44)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="2.527" classname="com.w2a.testingfranwork.testcases.DeleteCutsomerTest">
    <failure type="org.testng.TestNGException" message="java.util.concurrent.ExecutionException: java.lang.NullPointerException">
      <![CDATA[org.testng.TestNGException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
... 16 more
Caused by: java.lang.NullPointerException
at com.w2a.ApiTestingFrameowork.reports.ExtentListeners.onTestFailure(ExtentListeners.java:53)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
... 4 more
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="validateCreatecustomerAPIwithvalidSecretKey" time="2.51" classname="com.w2a.testingfranwork.testcases.createCustomerTest"/>
</testsuite> <!-- Create customer API Test -->
