<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-SQI1G9P" ignored="0" name="Delete customer API Test" tests="3" failures="3" timestamp="28 Dec 2021 19:03:02 GMT" time="3.297" errors="0">
  <testcase name="deleteCustomer" time="3.152" classname="com.w2a.testingfranwork.testcases.DeleteCutsomerTest">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.w2a.testingfranwork.testcases.DeleteCutsomerTest.deleteCustomer(DeleteCutsomerTest.java:44)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="3.154" classname="com.w2a.testingfranwork.testcases.DeleteCutsomerTest">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.w2a.testingfranwork.testcases.DeleteCutsomerTest.deleteCustomer(DeleteCutsomerTest.java:44)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="3.287" classname="com.w2a.testingfranwork.testcases.DeleteCutsomerTest">
    <failure type="org.testng.TestNGException" message="java.util.concurrent.ExecutionException: java.lang.NullPointerException">
      <![CDATA[org.testng.TestNGException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
... 13 more
Caused by: java.lang.NullPointerException
at com.w2a.ApiTestingFrameowork.reports.ExtentListeners.onTestFailure(ExtentListeners.java:63)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
... 4 more
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
</testsuite> <!-- Delete customer API Test -->
