<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-SQI1G9P" name="com.w2a.testingfranwork.testcases.DeleteCutsomerTest" tests="2" failures="0" timestamp="2021-12-24T23:20:19 IST" time="5.018" errors="2">
  <testcase name="deleteCustomer" time="2.510" classname="com.w2a.testingfranwork.testcases.DeleteCutsomerTest">
    <error type="junit.framework.ComparisonFailure" message="cus_KpxnyN1jeEeAjr expected:&lt;cus_KpxnyN1jeEeAjr&gt; but was:&lt;id not matching&gt;">
      <![CDATA[junit.framework.ComparisonFailure: cus_KpxnyN1jeEeAjr expected:<cus_KpxnyN1jeEeAjr> but was:<id not matching>
at junit.framework.Assert.assertEquals(Assert.java:81)
at com.w2a.testingfranwork.testcases.DeleteCutsomerTest.deleteCustomer(DeleteCutsomerTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- deleteCustomer -->
  <system-out/>
  <testcase name="deleteCustomer" time="2.508" classname="com.w2a.testingfranwork.testcases.DeleteCutsomerTest">
    <error type="junit.framework.ComparisonFailure" message="cus_KoeJP4LD1n0y2z expected:&lt;cus_KoeJP4LD1n0y2z&gt; but was:&lt;id not matching&gt;">
      <![CDATA[junit.framework.ComparisonFailure: cus_KoeJP4LD1n0y2z expected:<cus_KoeJP4LD1n0y2z> but was:<id not matching>
at junit.framework.Assert.assertEquals(Assert.java:81)
at com.w2a.testingfranwork.testcases.DeleteCutsomerTest.deleteCustomer(DeleteCutsomerTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- deleteCustomer -->
  <system-out/>
</testsuite> <!-- com.w2a.testingfranwork.testcases.DeleteCutsomerTest -->
